In [1]:

import numpy as np

list vs numpy time taken



In [2]:
from time import process_time

time taken by a list

In [5]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)




0.0


In [6]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)


0.0


# NUMPY ARRAYS

In [7]:
#list
list1 = [1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [8]:
np_array1 = np.array([1,2,3,4,5])
print(np_array1)
print(type(np_array1))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
#creating one dim array
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
 print(a.shape)

(5,)


In [13]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
print(b.shape)

(2, 4)


In [16]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


initial placeholder in numpy arrays

In [17]:
#create a numpy arrays of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
y = np.array((4,5))
print(y)

[4 5]


In [19]:
k = np.array([4,5])
print(k)

[4 5]


In [20]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
# array of particular values
o = np.full((4,5),5)
print(o)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [22]:
# create a identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
l = np.eye((7))
print(l)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [23]:
# create numpy arrays with random values
b = np.random.random((3,4))
print(b)

[[0.65115371 0.74149402 0.61800127 0.59891176]
 [0.43440754 0.84840466 0.93485525 0.64593612]
 [0.90938444 0.70947649 0.43108979 0.68118618]]


In [24]:
j = np.random.random((6,8))
print(j)

[[0.75359261 0.85390537 0.21582515 0.60329881 0.19808977 0.33798718
  0.46361001 0.84989221]
 [0.80126541 0.65340714 0.30690277 0.05733555 0.39022099 0.97323884
  0.97400798 0.43919247]
 [0.93200216 0.2021853  0.89152006 0.88050669 0.81267005 0.86587776
  0.32931686 0.68509528]
 [0.32622577 0.99281502 0.12582324 0.24298755 0.3095016  0.21956716
  0.58901972 0.40286685]
 [0.27968315 0.84772619 0.92547373 0.34423549 0.33855263 0.04822361
  0.04972465 0.10719773]
 [0.97043901 0.39893892 0.1667384  0.07323671 0.52616809 0.5667724
  0.30095747 0.30846807]]


In [26]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[21 45 59 47 66]
 [85 62 63 11 17]
 [31 86 28 31 80]]


In [27]:
# array of eventually spaced values
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [28]:
k = np.linspace(1,10,5)
print(k)

[ 1.    3.25  5.5   7.75 10.  ]


In [29]:
# array of evenly spaced values specifiying step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [30]:
p = np.arange(4,89,6)
print(p)

[ 4 10 16 22 28 34 40 46 52 58 64 70 76 82 88]


In [31]:
#convert a list to numpy array
list2 = [1,2,3,4,5]
nparray = np.asarray(list2)
print(nparray)
print(type(nparray))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [32]:
list3 = [10,20,30,40,50]
np_array1 = np.asarray(list3)
print(np_array1)
print(type(np_array1))

[10 20 30 40 50]
<class 'numpy.ndarray'>


# ANALYSING A NUMPY ARRAY

In [33]:
c = np.random.randint(10,100,(3,4))
print(c)

[[10 44 60 44]
 [55 52 25 91]
 [81 43 55 48]]


In [34]:
# array dimension
print(c.shape)

(3, 4)


In [35]:
# number of dimensions
print(c.ndim)

2


In [36]:
# number of element in array
print(c.size)

12


In [37]:
# checking the data type of values in the array
print(c.dtype)

int32


# MATHEMATICAL OPERATION ON A NP ARRAY

In [38]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2) # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [39]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[8 2 0]
 [2 5 3]
 [2 7 7]]
[[10 15 13]
 [19 14 13]
 [16 19 17]]


In [40]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[18 17 13]
 [21 19 16]
 [18 26 24]]
[[ -2 -13 -13]
 [-17  -9 -10]
 [-14 -12 -10]]
[[ 80  30   0]
 [ 38  70  39]
 [ 32 133 119]]
[[0.8        0.13333333 0.        ]
 [0.10526316 0.35714286 0.23076923]
 [0.125      0.36842105 0.41176471]]


In [42]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[4 1 1]
 [3 4 1]
 [8 9 2]]
[[12 18 12]
 [16 14 11]
 [11 17 14]]


In [43]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[16 19 13]
 [19 18 12]
 [19 26 16]]
[[ -8 -17 -11]
 [-13 -10 -10]
 [ -3  -8 -12]]
[[ 48  18  12]
 [ 48  56  11]
 [ 88 153  28]]
[[0.33333333 0.05555556 0.08333333]
 [0.1875     0.28571429 0.09090909]
 [0.72727273 0.52941176 0.14285714]]


# ARRAY MANIPULATION

In [48]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 5 4]
 [0 3 5]]
(2, 3)


In [49]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[5 0]
 [5 3]
 [4 5]]
(3, 2)


In [50]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 2 6]
 [4 6 2]]
(2, 3)


In [51]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[9 4]
 [2 6]
 [6 2]]
(3, 2)


In [52]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)


[[3 3 7]
 [7 9 4]]
(2, 3)


In [63]:
h = np.random.randint(5,78,(4,4))
print(h.shape)
print(h)

(4, 4)
[[21 76 75 33]
 [51 45  5 53]
 [75 75 29 42]
 [44 28 73 55]]


In [64]:
m = h.T
print(m)

[[21 51 75 44]
 [76 45 75 28]
 [75  5 29 73]
 [33 53 42 55]]
